language: nix
nix: 2.1.3

script:
  - nix-shell --pure --run './scripts/cibuild -Dnix=true'

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

install:
  - git clone https://github.com/urbit/arvo
  - cd ./arvo
  - git checkout $(cat ../.travis/pin-arvo-commit.txt)
  - cd ..

deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true # turn this off for official releases
  api_key:
    secure: V4E7784ECSS3MO6ZIRtang9XwibDyvDYGb0MoSaP2CTlmzIAhdokr4KJFM0qM4KRaaajCdQuqi0lojgOjwdxs7e0GkAwScb33LFxQ7Chj/QkFOY7V1AnSRLR5OsXnazB0nur5aSwvcvnggQ2XW3OeF7zIvGfs9aR97SEz/xCrVE=
  file: ./build/urbit # TODO upload package from before_deploy
  on:
    repo: urbit/urbit
    tags: true
